package com.model;


/**
 * TShouru generated by MyEclipse Persistence Tools
 */

public class TShouru implements java.io.Serializable
{

	private Integer id;
	private String shijian;
	private Double jine;
	private String chengyuan;

	private String leixing;
	private String beizhu;
	private Integer userId;
	
	
	public String getBeizhu()
	{
		return beizhu;
	}
	public void setBeizhu(String beizhu)
	{
		this.beizhu = beizhu;
	}
	public String getChengyuan()
	{
		return chengyuan;
	}
	public void setChengyuan(String chengyuan)
	{
		this.chengyuan = chengyuan;
	}
	public Integer getId()
	{
		return id;
	}
	public void setId(Integer id)
	{
		this.id = id;
	}
	public Double getJine()
	{
		return jine;
	}
	public void setJine(Double jine)
	{
		this.jine = jine;
	}
	public String getLeixing()
	{
		return leixing;
	}
	public void setLeixing(String leixing)
	{
		this.leixing = leixing;
	}
	
	public String getShijian()
	{
		return shijian;
	}
	public void setShijian(String shijian)
	{
		this.shijian = shijian;
	}
	public Integer getUserId()
	{
		return userId;
	}
	public void setUserId(Integer userId)
	{
		this.userId = userId;
	}

}